Add template for intranet deployments
4teamwork/ftw.bob.web pull request #119
Opened 2017-06-29 07:51 UTC by raphael-s

Adds a template to generate intranet platforms.

2017-06-29 08:40 UTC, elioschmutz requested changes
Die Bilder sind zusammen etwa 2 MB gross. Kannst du die auf eine maximale Breite von 800px runterskalieren? Das ist mehr als genug für Beispielbilder.

Ansonsten ist alles 👍

2017-06-29 08:40 UTC, elioschmutz commented on bobtemplates/intranet/+package.fullname+/+package.part_1+/+package.part_2+/viewlets/byline.py
> +class BaselDocumentBylineViewlet(DocumentBylineViewlet):
=> BaselDocumentBylineViewlet

2017-06-29 09:18 UTC, raphael-s commented
@elioschmutz Habe die Bilder auf insgesamt knapp 400kb herunter skaliert.

2017-07-03 11:29 UTC, elioschmutz approved these changes

2017-07-03 12:23 UTC, merged